import type { Metadata } from "next"

import "./globals.css"

import { Providers } from "@/components/Providers"

export const metadata: Metadata = {
    title: "AskCaloy",
    description: "Generated by create next app",
}

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="min-h-screen antialiased">
                <Providers>
                    <main className="h-screen bg-background text-foreground dark">{children}</main>
                </Providers>
            </body>
        </html>
    )
}
